---
- hosts: workers
  become: yes

  vars:
    container_name: worker
    docker_image: nginx
    docker_image_version_tag: 1.17.4
    container_port: 80
    host_port: 8088

  tasks:
    - name: Pull default Docker image
      docker_image:
        name: "{{ docker_image }}:{{ docker_image_version_tag }}"
        source: pull

    - name: Create containers
      docker_container:
        name: myworker
        image: "{{ docker_image }}:{{ docker_image_version_tag }}"
        ports:
          - "{{ host_port }}:{{ container_port }}"
        restart: true
        state: started
